### ISSUE TITLE
Glusterfs driver doesn't fail if the mount was not successful 

### ISSUE THREAD

**Issue by apollo13** [marcelo-ochoa/docker-volume-plugins#2]
Hi @marcelo-ochoa, thanks for enabling issues. I asked for it with a bit of self interest :) So, the issue currently is as follows: Glusterfs does not properly report failures via mount exit codes (see my glusterfs issue on https://github.com/gluster/glusterfs/issues/1693 -- there might be even more cases where this happens). Since glusterfs wrongly reports back zero as exit code, the docker driver does not know that mounting failed since it only checks the error code: https://github.com/marcelo-ochoa/docker-volume-plugins/blob/dc675c8bf4002abf83897b6cbf28dab090776df2/mounted-volume/driver.go#L236-L240 . Do you think it would make sense to execute `findmnt mountPoint` (https://linux.die.net/man/8/findmnt) to verify that the path actually got mounted and error out otherwise? This could be made optional by adding a flag to https://github.com/marcelo-ochoa/docker-volume-plugins/blob/dc675c8bf4002abf83897b6cbf28dab090776df2/mounted-volume/driver.go#L319 

As far as I understand it the `PostMount` hook cannot be utilized for that?

**To Reproduce**
1. Enable the glusterfs plugin
2. Create a volume with a subfolder that does not exist; vol1/sub1
3. Run an container with that volume attached
4. Note that the container starts without a mount

**Expected behavior**
An error should be thrown because the mount could not be established

**Server (please complete the following information):**
 - OS: Debian 10
 - Docker: 19.03.13

**Additional context**

**Comment by marcelo-ochoa** [comment]
@apollo13 I'll take a look to possible workaround about this problem.
findmnt is a good alternative, other option could be to use **df** command for the propagated mount and check that is glusterfs type.
The point is that debugging inside the plugin is not easy :(
Marcelo.

**Comment by marcelo-ochoa** [comment]
I'll check:
```
	cmd := exec.Command(p.mountExecutable, args...)
	if out, err := cmd.CombinedOutput(); err != nil {
		fmt.Printf("Command output: %s\n", out)
		return &volume.MountResponse{}, fmt.Errorf("error mounting %s: %s", req.Name, err.Error())
	} else {
		cmd := exec.Command("findmnt", mountPoint)
		if out, err := cmd.CombinedOutput(); err != nil {
			fmt.Printf("findmnt output: %s\n", out)
			return &volume.MountResponse{}, fmt.Errorf("error mounting %s: %s", req.Name, err.Error())
		}
	}
```
if it works.

**Comment by apollo13** [comment]
Yeah, it might be overkill though to add this to all plugins? I'd expect a nfs mount for instance to return the proper error code from `mount` already. Hence my suggestion to add an extra flag to `NewDriver`

**Comment by marcelo-ochoa** [comment]
Seem to work ok:
```
[root@node2 ~]# docker run -ti --rm -v myvolume/portaine:/mnt alpine sh
docker: Error response from daemon: VolumeDriver.Mount: error mounting myvolume/portaine: exit status 1.
See 'docker run --help'.
[root@node2 ~]# docker volume create -d glusterfs myvolume/portainer
myvolume/portainer
[root@node2 ~]# docker run -ti --rm -v myvolume/portainer:/mnt alpine sh
/ # ls -l /mnt
total 562
drwx------    2 root     root             6 Oct 25  2019 bin
drwx------    8 root     root            60 Oct  9 19:22 compose
-rw-r--r--    1 root     root           389 Oct 16 20:03 config.json
-rw-------    1 root     root        573440 Oct 27 19:48 portainer.db
-rw-------    1 root     root           227 Oct 25  2019 portainer.key
-rw-------    1 root     root           190 Oct 25  2019 portainer.pub
drwx------    2 root     root             6 Oct 25  2019 tls
```
I'll check if above addition works OK with s3fs driver too.
Marcelo.

**Comment by marcelo-ochoa** [comment]
The only check for other drivers is that the command _findmnt_ is installed on plugin image.
Whatever the file system is used _findmnt /propagated_mount_point_ must be valid.
Marcelo.

**Comment by marcelo-ochoa** [comment]
Finally fixed in [commit](https://github.com/marcelo-ochoa/docker-volume-plugins/commit/57722a81fd184c6da07bac001d89bf9f5aac7c9d)
Using **df** command I can avoid 40 Mb of extra image size for s3fs volume plugin.
I am uploading new release v2.0.5 to Docker Hub ASAP.

**Comment by apollo13** [comment]
Thanks, I just verified it on my box:
```
root@nomad03:~# docker run --rm -it --volume-driver glusterfs -v nomad/test333:/test centos:8 
docker: Error response from daemon: error while mounting volume '': VolumeDriver.Mount: error mounting nomad/test333:
Type
ext4

fstype should be glusterfs.
```
